### ISSUE TITLE
HTML5 Mode

### ISSUE THREAD

**Issue by arnaugarcia** [Corneyeski/ProyectoDAW#10]
Para que acabe de funcionar bien, en el fichero (https://github.com/Corneyeski/ProyectoDAW/blob/master/src/main/webapp/app/blocks/config/htl5.mode.config.js#L8) tenéis que poner 'proyectoApp' y luego en el index.html importar el fichero en cuestión (html5.mode.config.js). 

PD: Si tenéis websockets activos, absteneos de hacer lo ya que la consola se volverá roja con 4 clicks.

**Comment by AlexCasanova2** [comment]
Muchas Gracias @arnaugarcia !!
